import { useState } from 'react'
import { CDRLRow, AnchorRecord, UserRole } from '../types'
import { generateWeeklyReport, WeeklyReportResult } from '../utils/pdf'
import { AIRowInsight } from '../utils/aiAnalysis'

interface Props {
  data: CDRLRow[]
  anchors: Record<string, AnchorRecord>
  role: UserRole
  rowFindings: Record<string, string[]>
  contractRefs: Record<string, string>
  hullFilter?: string
  aiInsights?: Record<string, AIRowInsight>
  onClose: () => void
}

export default function ReportModal({ data, anchors, role, rowFindings, contractRefs, hullFilter, aiInsights, onClose }: Props) {
  const [report, setReport] = useState<WeeklyReportResult | null>(null)
  const [generating, setGenerating] = useState(false)
  const [progress, setProgress] = useState(0)

  const stats = {
    total: data.length,
    green: data.filter(r => r.status === 'green').length,
    yellow: data.filter(r => r.status === 'yellow').length,
    red: data.filter(r => r.status === 'red').length,
    sealed: Object.keys(anchors).length,
  }

  async function handleGenerate() {
    setGenerating(true)
    setProgress(0)

    // Simulate AI analysis phases
    const phases = [
      'Analyzing table data…',
      'Generating contractual references…',
      'Building priority assessment…',
      'Constructing RACI matrix…',
      'Computing progress metrics…',
      'Rendering PDF…',
    ]

    for (let i = 0; i < phases.length; i++) {
      setProgress(i + 1)
      await new Promise(r => setTimeout(r, 400 + Math.random() * 300))
    }

    const result = generateWeeklyReport(data, anchors, role, rowFindings, contractRefs, hullFilter, aiInsights)
    setReport(result)
    setGenerating(false)
  }

  function handleDownload() {
    if (!report) return
    const url = URL.createObjectURL(report.blob)
    const a = document.createElement('a')
    a.href = url
    a.download = report.filename
    a.click()
    URL.revokeObjectURL(url)
  }

  function handleEmail() {
    if (!report) return
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    const subject = encodeURIComponent(`S4 Systems DRL Weekly Status Report${hullFilter ? ` — ${hullFilter}` : ''} — ${dateStr}`)
    const body = encodeURIComponent(
      `Please find attached the S4 Systems DRL Weekly Status Report for ${dateStr}.\n\n` +
      `Summary:\n` +
      `• Total CDRLs: ${stats.total}\n` +
      `• Approved: ${stats.green}\n` +
      `• In Review: ${stats.yellow}\n` +
      `• Overdue: ${stats.red}\n` +
      `• Sealed to Ledger: ${stats.sealed}\n\n` +
      `All data has been verified and sealed to the XRPL.\n` +
      `Report generated by S4 Ledger™ Deliverables Tracker.\n\n` +
      `---\n` +
      `Note: The PDF report has been downloaded to your device. Please attach it to this email before sending.`
    )
    // Download the PDF first so user can attach it
    handleDownload()
    // Open email composer
    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="bg-white border border-border rounded-card p-6 max-w-xl w-full mx-4 animate-slideUp"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-red-500/10 flex items-center justify-center">
              <i className="fas fa-file-pdf text-red-500"></i>
            </div>
            <div>
              <h3 className="text-base font-bold text-gray-900">Generate Weekly PDF Report</h3>
              <p className="text-steel text-xs">AI-powered S4 Systems DRL Weekly Status Report{hullFilter ? ` — ${hullFilter}` : ''}</p>
            </div>
          </div>
          <button onClick={onClose} className="text-steel hover:text-gray-900 transition-colors">
            <i className="fas fa-times"></i>
          </button>
        </div>

        {/* Summary Preview */}
        <div className="grid grid-cols-5 gap-2 mb-5">
          <div className="bg-gray-50 rounded-lg p-2.5 text-center">
            <p className="text-lg font-bold text-gray-900">{stats.total}</p>
            <p className="text-[10px] text-steel uppercase tracking-wide">Total</p>
          </div>
          <div className="bg-green-50 rounded-lg p-2.5 text-center">
            <p className="text-lg font-bold text-green-500">{stats.green}</p>
            <p className="text-[10px] text-green-600 uppercase tracking-wide">Approved</p>
          </div>
          <div className="bg-yellow-50 rounded-lg p-2.5 text-center">
            <p className="text-lg font-bold text-yellow-500">{stats.yellow}</p>
            <p className="text-[10px] text-yellow-600 uppercase tracking-wide">In Review</p>
          </div>
          <div className="bg-red-50 rounded-lg p-2.5 text-center">
            <p className="text-lg font-bold text-red-500">{stats.red}</p>
            <p className="text-[10px] text-red-600 uppercase tracking-wide">Overdue</p>
          </div>
          <div className="bg-blue-50 rounded-lg p-2.5 text-center">
            <p className="text-lg font-bold text-accent">{stats.sealed}</p>
            <p className="text-[10px] text-accent uppercase tracking-wide">Sealed</p>
          </div>
        </div>

        {/* Report Contents Preview */}
        <div className="bg-gray-50 border border-border rounded-lg p-4 mb-5">
          <p className="text-xs font-semibold text-gray-900 mb-2">Report will include:</p>
          <div className="space-y-1.5">
            {[
              'Executive Summary with contractual analysis',
              'Key/Legend explaining status color codes',
              'Section 1: Top Priority DRLs sorted by criticality with DD Form 1423 references',
              'Section 2: Full Detailed List grouped by status with AI remarks',
              'Section 3: RACI Responsibility Matrix (Shipbuilder, SDM, Lead Reviewer, PM, QA)',
              'Section 4: Weekly Progress & Efficiency Analysis with time/cost savings',
              'Status Distribution visualization',
              'XRPL ledger verification proof on every page',
            ].map((item, i) => (
              <div key={i} className="flex items-start gap-2">
                <i className="fas fa-check-circle text-accent text-[10px] mt-0.5"></i>
                <p className="text-xs text-gray-700">{item}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Generate / Download / Email */}
        {!report ? (
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-accent hover:bg-accent/90 rounded-lg text-white text-sm font-semibold transition-all disabled:opacity-60"
          >
            {generating ? (
              <>
                <i className="fas fa-spinner fa-spin"></i>
                AI Analyzing… ({progress}/6)
              </>
            ) : (
              <>
                <i className="fas fa-brain mr-1"></i>
                Generate Weekly Report
              </>
            )}
          </button>
        ) : (
          <div className="space-y-2">
            <div className="flex items-center gap-2 p-3 bg-green-50 border border-green-200 rounded-lg mb-3">
              <i className="fas fa-check-circle text-green-500"></i>
              <p className="text-xs text-green-800 font-medium">
                Report generated successfully — {report.filename}
              </p>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <button
                onClick={handleDownload}
                className="flex items-center justify-center gap-2 px-4 py-3 bg-accent hover:bg-accent/90 rounded-lg text-white text-sm font-semibold transition-all"
              >
                <i className="fas fa-download"></i>
                Download PDF
              </button>
              <button
                onClick={handleEmail}
                className="flex items-center justify-center gap-2 px-4 py-3 bg-gray-900 hover:bg-gray-800 rounded-lg text-white text-sm font-semibold transition-all"
              >
                <i className="fas fa-envelope"></i>
                Open in Email
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
